version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: videohub-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-videohub}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres123}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - traefik-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache e sessões
  redis:
    image: redis:7-alpine
    container_name: videohub-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - traefik-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # pgAdmin para gerenciar PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: videohub-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin123}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - traefik-network
    restart: unless-stopped

  videohub:
    build:
      context: .
      args:
        - VITE_ADMIN_EMAIL=${VITE_ADMIN_EMAIL:-admin@example.com}
        - VITE_ADMIN_PASSWORD=${VITE_ADMIN_PASSWORD:-admin123}
        - VITE_DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    container_name: videohub-app
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/${POSTGRES_DB:-videohub}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis123}@redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      # Traefik labels para roteamento automático
      - "traefik.enable=true"
      - "traefik.http.routers.videohub.rule=Host(`${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.videohub.entrypoints=websecure"
      - "traefik.http.routers.videohub.tls.certresolver=letsencrypt"
      - "traefik.http.services.videohub.loadbalancer.server.port=80"
      # Middleware para HTTPS redirect
      - "traefik.http.middlewares.videohub-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.videohub-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.videohub-insecure.rule=Host(`${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.videohub-insecure.entrypoints=web"
      - "traefik.http.routers.videohub-insecure.middlewares=videohub-redirect"
    networks:
      - traefik-network
    restart: unless-stopped

  # Traefik reverse proxy
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      # API e Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-network"
      # Certificados SSL automáticos
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Logs
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard do Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt:/letsencrypt
    labels:
      # Dashboard do Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      # Autenticação básica para o dashboard
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USERS:-admin:$$2y$$10$$8K8TGFhQNmPYq8RQGv5HJOoP5b4b2J3xKj9mWoO2KpY8tFjJrQgXG}"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
    networks:
      - traefik-network
    restart: unless-stopped

  # Portainer para gerenciamento de containers
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - traefik-network
    restart: unless-stopped

networks:
  traefik-network:
    external: true

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  pgadmin-data:
    driver: local
  traefik-letsencrypt:
    driver: local
  portainer-data:
    driver: local