version: '3.8'

services:
  videohub:
    image: videohub-saas:latest
    container_name: videohub-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    labels:
      # Traefik labels para roteamento automático
      - "traefik.enable=true"
      - "traefik.http.routers.videohub.rule=Host(`${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.videohub.entrypoints=websecure"
      - "traefik.http.routers.videohub.tls.certresolver=letsencrypt"
      - "traefik.http.services.videohub.loadbalancer.server.port=80"
      # Middleware para HTTPS redirect
      - "traefik.http.middlewares.videohub-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.videohub-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.videohub-insecure.rule=Host(`${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.videohub-insecure.entrypoints=web"
      - "traefik.http.routers.videohub-insecure.middlewares=videohub-redirect"
    networks:
      - traefik-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  traefik-network:
    external: true

volumes:
  videohub-data:
    driver: local