version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: videohub-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin123}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-config:/pgadmin4/servers.json
    ports:
      - "8080:80"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${VIDEOHUB_DOMAIN:-localhost}`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      # Middleware de autenticação
      - "traefik.http.middlewares.pgadmin-auth.basicauth.users=${TRAEFIK_USERS:-admin:$$2y$$10$$8K8TGFhQNmPYq8RQGv5HJOoP5b4b2J3xKj9mWoO2KpY8tFjJrQgXG}"
      - "traefik.http.routers.pgadmin.middlewares=pgadmin-auth"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Configurador automático do pgAdmin (executa uma vez)
  pgadmin-config:
    image: alpine:latest
    container_name: videohub-pgadmin-config
    depends_on:
      pgadmin:
        condition: service_healthy
    networks:
      - traefik
    restart: "no"
    volumes:
      - pgadmin-config:/config
    command: |
      sh -c "
        echo '🔧 Configurando conexão automática do pgAdmin...'
        
        # Criar arquivo de configuração de servidores
        cat > /config/servers.json << 'EOF'
        {
          \"Servers\": {
            \"1\": {
              \"Name\": \"VideoHub PostgreSQL\",
              \"Group\": \"VideoHub\",
              \"Host\": \"videohub-postgres\",
              \"Port\": 5432,
              \"MaintenanceDB\": \"${POSTGRES_DB:-videohub}\",
              \"Username\": \"${POSTGRES_USER:-postgres}\",
              \"Password\": \"${POSTGRES_PASSWORD:-postgres123}\",
              \"SSLMode\": \"prefer\",
              \"Favorite\": true,
              \"Comment\": \"Banco principal do VideoHub SaaS\"
            }
          }
        }
        EOF
        
        echo '✅ Configuração do pgAdmin criada!'
        echo '🔗 Servidor PostgreSQL será conectado automaticamente'
        echo '📱 Acesse: http://localhost:8080 ou https://pgadmin.seudominio.com'
      "

volumes:
  pgadmin-data:
    driver: local
  pgadmin-config:
    driver: local

networks:
  traefik:
    external: true